export enum UkIconBgColor {
  TRANSPARENT = 'TRANSPARENT',
  BUTTON_PRIMARY = 'BUTTON-PRIMARY',
  OPACITY_PRIMARY_00 = 'OPACITY-PRIMARY-00',
  BUTTON_ERROR_FILL = 'BUTTON-ERROR-FILL',
}
export type IconBgColor = `${UkIconBgColor}`;

export enum UkIconBorderColor {
  TRANSPARENT = 'TRANSPARENT',
  BUTTON_ERROR_FILL = 'BUTTON-ERROR-FILL',
}
export type IconBorderColor = `${UkIconBorderColor}`;

export enum UkIconFgColor {
  BUTTON_PRIMARY = 'BUTTON-PRIMARY',
  CONTENT_LOW_EMPHASIS = 'CONTENT-LOW-EMPHASIS',
  CONTENT_HIGH_EMPHASIS = 'CONTENT-HIGH-EMPHASIS',
  CONTENT_PRIMARY = 'CONTENT-PRIMARY',
  CONTENT_NATURAL = 'CONTENT-NATURAL',
  CONTENT_CAUTION = 'CONTENT-CAUTION',
  CONTENT_SECONDARY = 'CONTENT-SECONDARY',
  CONTENT_LIGHT = 'CONTENT-LIGHT',
  CONTENT_ERROR = 'CONTENT-ERROR',
  CONTENT_PROGRESS = 'CONTENT-PROGRESS',
  CONTENT_SUCCESS = 'CONTENT-SUCCESS',
  REFERENCE_NEUTRAL = 'REFERENCE-NEUTRAL',
  CONTENT_DISABLED = 'CONTENT-DISABLED',
  REFERENCE_PRIMARY_LIGHT = 'REFERENCE-PRIMARY-LIGHT',
}
export type IconFgColor = `${UkIconFgColor}`;

export enum UkIconName {
  ARROW_DOWN = 'arrow_down',
  ARROW_LEFT = 'arrow_left',
  ARROW_RIGHT = 'arrow_right',
  ARROW_UP = 'arrow_up',
  CHECK_CHECK = 'check_check',
  CHECK_CHECK_SELECTED = 'check_check_selected',
  CHEVRON_DOWN = 'chevron_down',
  CHEVRON_LEFT = 'chevron_left',
  CHEVRON_RIGHT = 'chevron_right',
  CHEVRON_UP = 'chevron_up',
  CONTACT_CONTACT = 'contact_contact',
  CONTACT_CONTACT_SELECTED = 'contact_contact_selected',
  CUSTOMER_ADD_USER = 'customer_add_user',
  CUSTOMER_ALL = 'customer_all',
  CUSTOMER_CONTRACT = 'customer_contacts',
  CUSTOMER_EDIT_PROFILE = 'customer_edit_profile',
  CUSTOMER_GROUP = 'customer_group',
  CUSTOMER_USER = 'customer_user',
  CUSTOMER_USER_DELETE = 'customer_user_delete',
  DATE_CALENDAR = 'date_calendar',
  DATE_CLOCK = 'date_clock',
  DOWNLOAD_DOWNLOAD = 'download_download',
  DOWNLOAD_UPLOAD = 'download_upload',
  EDIT_EDIT = 'edit_edit',
  EDIT_EDIT_OUTLINE = 'edit_edit_outline',
  EMOJI_HAPPY = 'emoji_happy',
  EMOJI_LAUGH = 'emoji_laugh',
  EMOJI_MAD = 'emoji_mad',
  EMOJI_POKER = 'emoji_poker',
  EMOJI_SAD = 'emoji_sad',
  FINANCE_BANK_CARD = 'finance_bank_card',
  FINANCE_FINANCIAL_REPORT = 'finance_financial_report',
  FINANCE_GIFT = 'finance_gift',
  FINANCE_GIFT_CARD = 'finance_gift_card',
  FINANCE_LOVE_CARD = 'finance_love_card',
  FINANCE_MONEY = 'finance_money',
  FINANCE_TERMINAL = 'finance_terminal',
  FINANCE_WALLET = 'finance_wallet',
  FINANCIAL_CARTABLE = 'financial_cartable',
  GENERAL_CALL_CENTER = 'general_call_center',
  GENERAL_COPY = 'general_copy',
  GENERAL_DELETE = 'general_delete',
  GENERAL_EMPTY_STATE = 'general_empty_state',
  GENERAL_EXIT = 'general_exit',
  GENERAL_FILTER = 'general_filter',
  GENERAL_MORE = 'general_more',
  GENERAL_NOTIFICATION = 'general_notification',
  GENERAL_RETRY = 'general_retry',
  GENERAL_SEARCH = 'general_search',
  GENERAL_SEARCH_FILTER = 'general_search_filter',
  GENERAL_SETTING = 'general_setting',
  GENERAL_SHARE = 'general_share',
  GENERAL_VIEW = 'general_view',
  GENERAL_ACCESS = 'general_access',
  GENERAL_SECURITY = 'general_security',
  GENERAL_FILE = 'general_file',
  GENERAL_FILM = 'general_film',
  GENERAL_IMAGE = 'general_image',
  HOME_HOME = 'home_home',
  HOME_HOME_SELECTED = 'home_home_selected',
  INFO_INFO = 'info_info',
  INFO_INFO_OUTLINE = 'info_info_outline',
  LINK_BLOG = 'link_blog',
  LINK_CATALOG = 'link_catalog',
  LINK_CUSTOMER_INFO = 'link_customer_info',
  LINK_LINK = 'link_link',
  LINK_MENU = 'link_menu',
  LINK_LINK_OUTLINE = 'link_link_outline',
  LINK_LINK_SELECTED = 'link_link_selected',
  LINK_VISIT_CARD = 'link_visit_card',
  LINK_WEB = 'link_web',
  MARKETING_MARKETING = 'marketing_marketing',
  MARKETING_MARKETING_SELECTED = 'marketing_marketing_selected',
  MATH_CHECK = 'math_check',
  MATH_CHECK_OUTLINE = 'math_check_outline',
  MATH_CLOSE = 'math_close',
  MATH_CLOSE_OUTLINE = 'math_close_outline',
  MATH_MINUS = 'math_minus',
  MATH_MINUS_OUTLINE = 'math_minus_outline',
  MATH_PLUS = 'math_plus',
  MATH_PLUS_OUTLINE = 'math_plus_outline',
  MSG_CLOSE = 'msg_close',
  MSG_EDIT = 'msg_edit',
  MSG_NORMAL = 'msg_normal',
  MSG_SEND = 'msg_send',
  MSG_SENDING = 'msg_sending',
  MSG_TYPE_LOVE = 'msg_type_love',
  MSG_TYPE_SIMPLE = 'msg_type_simple',
  MSG_TYPE_SMILE = 'msg_type_smile',
  MSG_TYPE_SURVEY = 'msg_type_survey',
  MSG_TYPE_THANKS = 'msg_type_thanks',
  MSG_WAIT = 'msg_wait',
  PROFILE_NOT_SELECTED = 'profile_not_selected',
  PROFILE_SELECTED = 'profile_selected',
  QUESTION_QUESTION = 'question_question',
  QUESTION_QUESTION_OUTLINE = 'question_question_outline',
  RADIO_RADIO_NOT_SELECTED = 'radio_radio_not_selected',
  SEND_MESSAGE_SEND = 'send_message_send',
  SEND_MESSAGE_SEND_SELECTED = 'send_message_send_selected',
  SORT_DOWN = 'sort_down',
  SORT_UP = 'sort_up',
  STORE_DIRECTION = 'store_direction',
  STORE_LOCATION = 'store_location',
  STORE_MOBILE = 'store_mobile',
  STORE_PHONE = 'store_phone',
  STORE_STORE = 'store_store',
  STORE_TROLLY = 'store_trolly',
  TOGGLE_OFF = 'toggle_off',
  TOGGLE_ON = 'toggle_on',
  TREND_DOWN = 'trend_down',
  TREND_DOWN_OUTLINE = 'trend_down_outline',
  TREND_UP = 'trend_up',
  TREND_UP_OUTLINE = 'trend_up_outline',
  //
  SETTINGS_SUN = 'settings_sun',
  SETTINGS_MOON = 'settings_moon',
  SETTINGS_SETTING = 'settings_setting',
  LOCK_AFTER = 'lock_after',
  LOCK_PRE = 'lock_pre',
  LOCK_PROGRESS = 'lock_progress',
  UNLOCK_AFTER = 'unlock_after',
  USER_ACCESS = 'user_access',
  BADGE_OK = 'badge_ok',
  GENERAL_REDO = 'general_redo',
  GENERAL_REFRESH = 'general_refresh',
  GENERAL_CAKE = 'general_cake',
  GENERAL_SHAKE_HAND = 'general_shake_hand',
  LINK_SPINNER = 'link_spinner',
  LINK_CHART = 'link_chart',
  GENERAL_COPY_CLIPBOARD = 'general_copy_clipboard',
  GENERAL_DEBUG = 'general_debug',
  GENERAL_ANDROID = 'general_android',
  GENERAL_ACADEMY = 'general_academy',
  GENERAL_ACADEMY_PLAY_CONTENT = 'general_academy_play_content',
  GENERAL_ACADEMY_PLAY = 'general_academy_play',
  GENERAL_ACADEMY_CONTENT = 'general_academy_content',
  GENERAL_LOADING = 'general_loading',
  //
  REGISTER_CARTABLE = 'register_cartable',
}
export type IconName = `${UkIconName}`;

export enum UkIconSize {
  SMALLEST = 'SMALLEST',
  SMALLER = 'SMALLER',
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
  LARGER = 'LARGER',
  LARGEST = 'LARGEST',
  LARGEST_B_X = 'LARGEST-B-X',
  LARGEST_X = 'LARGEST-X',
  LARGEST_XX = 'LARGEST-XX',
  LARGEST_XXX = 'LARGEST-XXX',
  LARGEST_XXXX = 'LARGEST-XXXX',
}
export type IconSize = `${UkIconSize}`;

export enum UkIconCursor {
  DEFAULT = 'DEFAULT',
  POINTER = 'POINTER',
}
export type IconCursor = `${UkIconCursor}`;
