export enum UkStoringProperty {
  USER_INFO = 'USER_INFO',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRATION = 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRATION = 'REFRESH_TOKEN_EXPIRATION',
  USER_CONFIGURATION = 'USER_CONFIGURATION',
  GENERAL_CONFIGURATION = 'GENERAL_CONFIGURATION',
  SHOP_ID = 'SHOP_ID',
  USER_DATA = 'USER_DATA',
  //
  // TODO: remove old props
  TOKEN_EXPIRATION = 'TOKEN_EXPIRATION',
  REFRESH_EXPIRATION = 'REFRESH_EXPIRATION',
}
